# Generated by Django 5.0.2 on 2024-05-13 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_datecompleted'),
        ('todo', '0002_auto_20200131_0131'),
    ]

    operations = [
    ]
